version: 2.1

executors:
  golang:
    parameters:
      version:
        type: enum
        enum: ['1.12-rc', '1.11.5']
    docker:
      - image: circleci/golang:<< parameters.version >>

jobs:
  test:
    parameters:
      exec:
        type: executor
      cover:
        default: false
        type: boolean
    executor: << parameters.exec >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod/cache"
      - when:
          condition: << parameters.cover >>
          steps:
            - run: go test -coverpkg ./... -coverprofile coverage.txt -covermode atomic -race -v ./...
            - run: bash <(curl -s https://codecov.io/bash)
      - unless:
          condition: << parameters.cover >>
          steps:
            - run: go test -race -v ./...
  e2e:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    docker:
      - image: google/cloud-sdk:174.0.0
        command: [gcloud, beta, emulators, pubsub, start, '--host-port=localhost:8085']
    environment:
      PUBSUB_EMULATOR_HOST: localhost:8085
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod/cache"
      - run:
        name: install dockerize
        command: curl -sfL https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar -C /usr/local/bin -xzv
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
        name: Wait for pubsub emulator
        command: dockerize -wait tcp://${PUBSUB_EMULATOR_HOST} -timeout 1m
      - run: go test -v ./_tests/cloudpubsub

workflows:
  version: 2
  test:
    jobs:
      - test:
          name: 1.12-rc
          cover: true
          exec:
            name: golang
            version: 1.12-rc
      - test:
          name: 1.11.5
          exec:
            name: golang
            version: 1.11.5
      - e2e:
          name: 1.12-rc
          exec:
            name: golang
            version: 1.12-rc
      - e2e:
          name: 1.11.5
          exec:
            name: golang
            version: 1.11.5
